[package]
name = "minigame"
version = "0.1.0"
authors = [ "Valerio Santinelli <santinelli@gmail.com>" ]
build = "build.rs"

[dependencies]
dynamic_reload = {version = "0.2.1", optional=true}
sdl2 = { version = "0.31.0", default-features = false, features = ["unsafe_textures", "ttf"] }
cgmath = "0.14.1"
rusttype = "0.6"
png = "0.7.0"
rand = "*"
log = "0.3.8"
imgui = "0.0.15"
stb_image = "0.2.2"

[build-dependencies]
gl_generator = "0.5.3"

[features]
hotload = ["dynamic_reload"]
default = ["hotload"]

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.4", default-features = false }

[lib]
name = "minigame"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "main"
path = "src/main.rs"
